### ISSUE TITLE
layout changed

### ISSUE THREAD

**Issue by sp2003** [jeanmarc77/meterN#10]
I'm not sure how, but the layout of the histogram for the last 15 days has changed like this. Can it be restored?
Perhaps an update of Raspbian Buster?
<img width="1664" alt="Immagine 2023-04-26 083841" src="https://user-images.githubusercontent.com/34820831/234490691-15abebbb-5ff8-419e-889a-5d8a396ee40a.png">

**Comment by sp2003** [comment]
OMG, the histogram is back but the gauge is gone!
<img width="569" alt="Immagine 2023-04-26 092429" src="https://user-images.githubusercontent.com/34820831/234500795-fa8b86db-b26e-4b59-919c-cfd67d7cb453.png">

**Comment by jeanmarc77** [comment]
Hi,
Thanks for notifiying. It's because Highcharts lib turn to 11, i have to update the code.
I dont have issue with the gauge though

**Comment by sp2003** [comment]
hi
i updated php to 8.2 and the gauge is back.  The problem remains with the histogram

**Comment by jeanmarc77** [comment]
Can you try with this one ? Please report any other graph issue.
https://github.com/jeanmarc77/meterN/blob/main/index.php

**Comment by sp2003** [comment]
The histogram had returned after updating PHP to 8.2, however, I still modified Metern's index.php as you did. I didn't do anything for 123solar.
The problem is with the MeterN and 123solar gauge.

**Comment by jeanmarc77** [comment]
The graphs have nothing to do with PHP, i already use  8.2.4.
Make sure you force refresh your browser cache (CTRL +F5) to get the latest libs.

**Comment by sp2003** [comment]
You are right!

can index.php also be edited for 123solar?

**Comment by jeanmarc77** [comment]
it's already done for 123s :)

**Comment by sp2003** [comment]
Meaning what? can I replace the index.php you made today in /var/www/123solar/ ?

**Comment by jeanmarc77** [comment]
https://github.com/jeanmarc77/123solar/blob/main/index.php

**Comment by sp2003** [comment]
perfect!!

thank you very much

**Comment by EnviroA** [comment]
I just updated links.php within the scripts folder and updated it to use the previous version of highcharts 10.3.2
clear browser cache and it works as before,

$HC       = "https://code.highcharts.com/10.3.2/highcharts.js";
$HCmore   = "https://code.highcharts.com/10.3.2/highcharts-more.js";

cheers

**Comment by jeanmarc77** [comment]
I notice no more issues with the fix (cache cleared) on various environnements (OS/Browser)

**Comment by aszczupal** [comment]
Hi @jeanmarc77 , I still using version 1.2.3 , and "last 15 days" looking wrong.. , I can;t use "auto update" Because of wrong URL' (old site) , Could You write a short instruction how to update/upgrade on Wiki ? ( forum dissapeared )
Regards
Adam

**Comment by jeanmarc77** [comment]
@aszczupal check wiki
Extract the latest archive on your web server's folder. (tar -xzvf 123solar*.tar.gz)
Import your previous "data" & "config" directories. Then, go into the 123Solar administration.

**Comment by sp2003** [comment]
> https://github.com/jeanmarc77/123solar/blob/main/index.php
hi JM
i have a problem with 123solar.
When starting the PI, 123solar doesn't start automatically, but I have to do it from the admin page.
of course I did

`systemctl enable 123solar.service`

and that is service.

```
[Unit]
Description=123Solar
Requires=network.target
After=network.target apache2.service php-fpm.service

[Service]
Type=onesh
Execstart=/bin/sleep 10
ExecStart=/usr/bin/curl http://localhost/123solar/scripts/boot123s.php
#ExecStart=/usr/bin/curl --insecure https://localhost/123solar/scripts/boot123s.php

[Install]
WantedBy=default.target
#WantedBy=multi-user.target
```
Could the php8.2 upgrade be the cause?
With MeterN there is no problem.

**Comment by jeanmarc77** [comment]
all ok guys
