### ISSUE TITLE
help third counter

### ISSUE THREAD

**Issue by wifi75** [jeanmarc77/meterN#11]
hello I added a third counter sdm120 and set id 10, now I have a counter id 1 production, counter id 2 home consumption, while the third id 10 electric car consumption.
i set the file config_daemon.php like below:
```
<?php
if(!defined('checkaccess')){die('Direct access not permitted');}
// Manage com. apps daemon as 'http' user if needed

if (is_null($PID)) { // Stop Daemon
	exec("pkill -f pooler485 > /dev/null 2>&1 &");
	#exec("pkill -f loadcheck > /dev/null 2>&1 &");	
} else { //Start
	exec("pooler485 1,2,10 9600 /dev/ttyUSB0 > /dev/null 2>/dev/null &");
	#exec("loadcheck > /dev/null 2>/dev/null &");
}
?>

```
on the folder dev/shm there is metern10.txt file with this data
```
10(3215.40*W)
10(28211*Wh)
10_1(232.80*V)
10_2(13.90*A)
10_3(50.00*Hz)
10_4(1.00*F)
```

 but after test on meterN admin panel
![image](https://github.com/jeanmarc77/meterN/assets/31816231/0fcff30c-3299-44c5-a71e-0032304671b8)

energy test nont working:

![image](https://github.com/jeanmarc77/meterN/assets/31816231/1a232c0e-4f58-4bf3-aff9-75dcacc2df97)

while power is correct:

![image](https://github.com/jeanmarc77/meterN/assets/31816231/5787b6c6-4fa5-4393-90c0-47860c7881b8)

in fact it doesn't create the graph with the consumed energy of the counter id 10.

this is my file allowed_comapps.php:

```
<?php
if(!defined('checkaccess')){die('Direct access not permitted');}
// For safety reason, manually complete this data array to permit mN to use those commands
// Keep 'http' user file permission
$ALLWDCMD[0] = 'pool123s energy';
$ALLWDCMD[1] = 'pool123s power';
$ALLWDCMD[2] = 'poolerconsumi 2 energy';
$ALLWDCMD[3] = 'poolerconsumi 2 power';
$ALLWDCMD[4] = 'virtmeter 3 0 0 impenergy 0';
$ALLWDCMD[5] = 'virtmeter 3 0 0 imppower 0';
$ALLWDCMD[6] = 'virtmeter 4 0 0 expenergy 0';
$ALLWDCMD[7] = 'virtmeter 4 0 0 exppower 0';
$ALLWDCMD[8] = 'virtmeter 5 0 0 selfcenergy 0';
$ALLWDCMD[9] = 'virtmeter 5 0 0 selfcpower 0';
$ALLWDCMD[10] = 'virtmeter 6 3 0 energy F1';
$ALLWDCMD[11] = 'virtmeter 6 3 0 power F1';
$ALLWDCMD[12] = 'virtmeter 7 3 0 energy F2';
$ALLWDCMD[13] = 'virtmeter 7 3 0 power F2';
$ALLWDCMD[14] = 'virtmeter 8 3 0 energy F3';
$ALLWDCMD[15] = 'virtmeter 8 3 0 power F3';
$ALLWDCMD[16] = 'virtmeter 9 3 0 energy F23';
$ALLWDCMD[17] = 'virtmeter 9 3 0 power F23';
$ALLWDCMD[18] = 'reqsdm tensione';
$ALLWDCMD[19] = 'reqsdm corrente';
$ALLWDCMD[20] = 'reqsdm cospi';
$ALLWDCMD[21] = 'poolerconsumi 10 energy';
$ALLWDCMD[22] = 'poolerconsumi 10 power';
?>

```

can you help me to solve the problem?

**Comment by jeanmarc77** [comment]
do you use latest version ?
i think [i have changed the dataset](https://github.com/jeanmarc77/meterN/commit/0f5dd57d3d89a663067ab5b4bc5d3127fce91d0f) a while ago as it work

```
<?php
$id = '10';
$datareturn = "10(0*Wh)";

function isvalid($id, $datareturn) //  IEC 62056 data set structure
{
	$regexp = "/^$id\(.+".'\x00'."*.+\)$/i"; //ID(VALUE*UNIT)
	if (preg_match($regexp, $datareturn)) {
		$datareturn = preg_replace("/^$id\(/i", '', $datareturn, 1); // VALUE*UNIT)
		$datareturn = preg_replace("/\*.+\)$/i", '', $datareturn, 1); // VALUE
		if(empty($datareturn)) {
			$datareturn = 'empty';
		}
	} else {
		$datareturn = null;
	}
	return $datareturn;
}
echo $datareturn;
?>
```

**Comment by wifi75** [comment]
> do you use latest version ? i think [i have changed the dataset](https://github.com/jeanmarc77/meterN/commit/0f5dd57d3d89a663067ab5b4bc5d3127fce91d0f) a while ago as it work
> 
> ```
> <?php
> $id = '10';
> $datareturn = "10(0*Wh)";
> 
> function isvalid($id, $datareturn) //  IEC 62056 data set structure
> {
> 	$regexp = "/^$id\(.+".'\x00'."*.+\)$/i"; //ID(VALUE*UNIT)
> 	if (preg_match($regexp, $datareturn)) {
> 		$datareturn = preg_replace("/^$id\(/i", '', $datareturn, 1); // VALUE*UNIT)
> 		$datareturn = preg_replace("/\*.+\)$/i", '', $datareturn, 1); // VALUE
> 		if(empty($datareturn)) {
> 			$datareturn = 'empty';
> 		}
> 	} else {
> 		$datareturn = null;
> 	}
> 	return $datareturn;
> }
> echo $datareturn;
> ?>
> ```


Yes I have  last version of meterN 1.2.4.1.

this is my folder shm:
![image](https://github.com/jeanmarc77/meterN/assets/31816231/5833f05e-2874-473b-a3af-1673e7786c7e)
but the consumi10.txt file is empty
`10(0*Wh)`

I don't understand what I have to change again....

**Comment by jeanmarc77** [comment]
i don't know much about poolerconsumi. what does it returns from cli ?

**Comment by wifi75** [comment]
> i don't know much about poolerconsumi. what does it returns from cli ?

![image](https://github.com/jeanmarc77/meterN/assets/31816231/2c19b97d-8ca5-495c-a743-2c6e2c1deceb)

**Comment by jeanmarc77** [comment]
from terminal..

**Comment by wifi75** [comment]
what command should i run?

**Comment by jeanmarc77** [comment]
poolerconsumi 10 energy

**Comment by wifi75** [comment]
> poolerconsumi 10 energy

![image](https://github.com/jeanmarc77/meterN/assets/31816231/40cf0368-14a0-4b04-9b1b-eabec2c5c3a4)

**Comment by jeanmarc77** [comment]
and "more metern/scripts/datasets/IEC62056.php" ?

**Comment by wifi75** [comment]
I have never edited anything that file... what should I do there?

**Comment by jeanmarc77** [comment]
show me what that contains..

**Comment by wifi75** [comment]
> show me what that contains..

```
<?php
function isvalid($id, $datareturn) //  IEC 62056 data set structure
{
	$regexp = "/^$id\(.+".'\x00'."*.+\)$/i"; //ID(VALUE*UNIT)
	if (preg_match($regexp, $datareturn)) {
		$datareturn = preg_replace("/^$id\(/i", '', $datareturn, 1); // VALUE*UNIT)
		$datareturn = preg_replace("/\*.+\)$/i", '', $datareturn, 1); // VALUE
		if(empty($datareturn)) {
			$datareturn = 'empty';
		}
	} else {
		$datareturn = null;
	}
	return $datareturn;
}
?>
```

**Comment by jeanmarc77** [comment]
try [this one](https://github.com/jeanmarc77/meterN/blob/main/scripts/datasets/IEC62056.php)
that said, your "poolerconsumi 10 energy" returns 0 while it should give a number

**Comment by wifi75** [comment]
poolerconsumi I already use it for home consumption and it works well.

I tried your file but nothing changed.

**Comment by wifi75** [comment]
hello now work but it doesn't generate the graph in home:

![image](https://github.com/jeanmarc77/meterN/assets/31816231/843edae6-456d-4271-a6ec-5e8197264ede)

layout is enabled...
![image](https://github.com/jeanmarc77/meterN/assets/31816231/301cf56c-d434-4598-90d1-f8c04387bfa4)

also deatail work:
![image](https://github.com/jeanmarc77/meterN/assets/31816231/1a2e823d-cc93-4fa4-b37e-7d6588d0a72d)
what can i check?

**Comment by wifi75** [comment]
hello I discovered that after the last update of this morning 1.2.4.1 the graph of the electric car id10 disappears.

**Comment by jeanmarc77** [comment]
Could you give the url of your logger and delete the message right after ?

**Comment by wifi75** [comment]
> Could you give the url of your logger and delete the message right after ?

https://solar.iu3cyv.eu/

**Comment by jeanmarc77** [comment]
I think it's because your Auto_elettrica have bad values in csv like [1684098300000,""] [1684054800000,"0"] [1684104900000,"5942"]
metern/programs/programmeter.php
You may wait few hours it will be ok

**Comment by wifi75** [comment]
> 

which is the csv file that I am going to correct it?

**Comment by jeanmarc77** [comment]
you can edit metern/data/csv/20150515.csv & 20150514.csv (keep RW permissions)

**Comment by wifi75** [comment]
> you can edit metern/data/csv/20150515.csv & 20150514.csv (keep RW permissions)

files look fine...
I don't understand where is the error...
try to look too...

[20230514.csv](https://github.com/jeanmarc77/meterN/files/11475031/20230514.csv)
[20230515.csv](https://github.com/jeanmarc77/meterN/files/11475032/20230515.csv)

**Comment by wifi75** [comment]
> you can edit metern/data/csv/20150515.csv & 20150514.csv (keep RW permissions)

sorry but I don't have file 20150515.csv

**Comment by wifi75** [comment]
the file 20150515.csv does not exist

**Comment by jeanmarc77** [comment]
20230515.csv sorry, i don't have time to look at it right now. Try to see if it contains quoted values

**Comment by wifi75** [comment]
> 1684104900000,"5942

I looked carefully, there are no outliers, everything is ok!

**Comment by jeanmarc77** [comment]
quoted values have wrong format "0", "" or "5942"

**Comment by wifi75** [comment]
I removed the 0s now it's ok it works!

**Comment by wifi75** [comment]
once there was an online forum now it's gone, I remember that I found them the step by step guide to install 123solar a meter on ubuntu.
there is no longer that guide ... do you know where I can find it?

**Comment by jeanmarc77** [comment]
I dunno, please only use git for application issue and not for help, i don't have time for that sorry
