### ISSUE TITLE
grafich

### ISSUE THREAD

**Issue by wifi75** [jeanmarc77/meterN#12]
hello now there are no loads, but why is the graph like this??

![image](https://github.com/jeanmarc77/meterN/assets/31816231/6d328396-6f30-4689-a56a-14b927bc503d)

**Comment by jeanmarc77** [comment]
it happen when there is full 0 values.
Please stop filling bug report as they are not

**Comment by wifi75** [comment]
forgive me but I think there is something wrong,
that counter hasn't changed for several days, yet he continued to count on May 16 and 17.
I have no longer connected the car to recharge, yet as you can see from the 15-day graph, the one with the color or, it tells me that there is consumption.
but is not so...

![image](https://github.com/jeanmarc77/meterN/assets/31816231/6f7ccb14-61bd-4ee2-bdd9-0230ab529c49)

**Comment by jeanmarc77** [comment]
what are the first and last values in your daily csv (20220516 & 20020517.csv) for this meter ?
what value is shown when the mouse is over the bar ?

**Comment by wifi75** [comment]
the first and last values for daily csv (20220516 & 20020517.csv is 52191
see below 
![image](https://github.com/jeanmarc77/meterN/assets/31816231/cd6b7b5b-eff0-493c-8f84-7f1f64f0f84c)

![image](https://github.com/jeanmarc77/meterN/assets/31816231/dd315f82-231a-479c-b3fb-4c6a791f1803)

**Comment by jeanmarc77** [comment]
can you send your csv ? 
btw: your babies are cute ;)

**Comment by wifi75** [comment]
yes
[20230517.csv](https://github.com/jeanmarc77/meterN/files/11509763/20230517.csv)
[20230516.csv](https://github.com/jeanmarc77/meterN/files/11509764/20230516.csv)

**Comment by jeanmarc77** [comment]
odd... and data/meters/10xxx2023.csv ?

**Comment by wifi75** [comment]
[10Auto_elettrica2023.csv](https://github.com/jeanmarc77/meterN/files/11509826/10Auto_elettrica2023.csv)

**Comment by jeanmarc77** [comment]
for unknown reason your meter give several value for the same day
maybe reboot your sytem

**Comment by wifi75** [comment]
I reboot Now...

**Comment by wifi75** [comment]
In your opinion, if I click on the decommisioning button and reset the car counter can it work properly again?
![image](https://github.com/jeanmarc77/meterN/assets/31816231/521fd27f-3a5f-453f-a247-5e5f21699501)

**Comment by jeanmarc77** [comment]
I never seen that, they must be something wrong in your cfg files.
Your meter gave 2 values for the same day [1684368000000,0],[1684368000000,13.256]
did you have set another meter with meter ID '10' ?

**Comment by jeanmarc77** [comment]
i guess that 'Autoconsumo' same as 'Auto_elettrica'..

**Comment by wifi75** [comment]
absolutely not, sAutoconsumo is another matter.

**Comment by jeanmarc77** [comment]
it mess up with Autoconsumo meter. Can you give config/config_layout.php file ?

**Comment by wifi75** [comment]
yes, below

[config_layout.zip](https://github.com/jeanmarc77/meterN/files/11516918/config_layout.zip)

**Comment by jeanmarc77** [comment]
ok try this https://github.com/jeanmarc77/meterN/blob/main/programs/programlastdays.php

**Comment by wifi75** [comment]
omg it seems to work for me
see my link

**Comment by wifi75** [comment]
while for the graph with the counter at 0 it can't be fixed ?

![image](https://github.com/jeanmarc77/meterN/assets/31816231/f455d041-0eeb-43d5-b7d5-8826407c6fda)

**Comment by jeanmarc77** [comment]
try this https://github.com/jeanmarc77/meterN/blob/main/index.php

**Comment by wifi75** [comment]
ok i also replaced index.php... i don't see any difference, maybe we have to wait?

**Comment by jeanmarc77** [comment]
so this https://github.com/jeanmarc77/meterN/blob/main/index.php

**Comment by wifi75** [comment]
> so this https://github.com/jeanmarc77/meterN/blob/main/index.php

yesss !!! seems to work, see for yourself on my url

thank you

**Comment by jeanmarc77** [comment]
neat

**Comment by wifi75** [comment]
hello just to let you know that all the changes you made worked perfectly.
last week I loaded the car and everything was written correctly, see graph.
Thank you for your precious support!

![image](https://github.com/jeanmarc77/meterN/assets/31816231/821d28a2-0a8c-494b-9967-ad7545e42b9b)
