### ISSUE TITLE
Interrupted graph

### ISSUE THREAD

**Issue by flanesi** [jeanmarc77/meterN#13]
Hi Jeanmarc,
i have this weird situation with interrupted graph with MeterN 1.2.4.1
![Screen Shot 07-28-23 at 11 09 AM](https://github.com/jeanmarc77/meterN/assets/8526796/6969fc2b-2d3d-4925-9ea3-3b3f6d93f3f0)

I did a few restarts of the raspberry in that time but the csv file is correctly populated (excluding the missing value of 8:00).

![Screen Shot 07-28-23 at 11 11 AM](https://github.com/jeanmarc77/meterN/assets/8526796/6831519d-3afe-41c9-bf82-01f4a6740b6e)
What can it depend on? 
Or is it normal?
Thanks

**Comment by jeanmarc77** [comment]
You had missing samples à 8:00 hence the issue
