### ISSUE TITLE
missing charts for eflow calls

### ISSUE THREAD

**Issue by sp2003** [jeanmarc77/meterN#14]
Hello everyone,

I don't remember if it was after an update, but the graphs related to the eflow calls (withdrawals, inputs, and self-consumption) are not being generated, while the values are displayed. I suspect it's a PHP error, but I don't know where to intervene. The php.ini file is correctly modified.

how can i solve?
![Immagine 2023-09-06 100917](https://github.com/jeanmarc77/meterN/assets/34820831/cc3525de-ac73-4543-a69a-664156ca57f1)
![Immagine 2023-09-06 101052](https://github.com/jeanmarc77/meterN/assets/34820831/9d55c2ab-1bd9-4193-8203-0d8fddcb2638)
![Immagine 2023-09-06 100830](https://github.com/jeanmarc77/meterN/assets/34820831/23f01967-2fda-4331-ac55-4cc27b98106f)

**Comment by jeanmarc77** [comment]
Hi,
Sorry i don't support third party's com apps and i did not write the eflow your are using (i writed houseenergy.php years ago)
