### ISSUE TITLE
new year 2024

### ISSUE THREAD

**Issue by wifi75** [jeanmarc77/meterN#17]
hello why do not see new year 2024?

![image](https://github.com/jeanmarc77/meterN/assets/31816231/cc47551e-15ab-411f-bb08-c078221f41db)
but in detali menu it is ok
![image](https://github.com/jeanmarc77/meterN/assets/31816231/147016b9-d580-477c-9adf-064f5a0ee46f)

see below folder permission
![image](https://github.com/jeanmarc77/meterN/assets/31816231/32fecfb6-4354-45cb-939e-6058af4cc5f5)

![image](https://github.com/jeanmarc77/meterN/assets/31816231/f858d8e3-11e7-4d58-be7c-011ff48078ff)

**Comment by jeanmarc77** [comment]
Hi,
It is the desired behavior, there is nothing much to show with only 1 day of data.

**Comment by wifi75** [comment]
true!!!!
sorry and HNY
![image](https://github.com/jeanmarc77/meterN/assets/31816231/b44a4e4c-d1e9-45df-ab25-ec3c71b34040)
