### ISSUE TITLE
automatic scaling of y axe

### ISSUE THREAD

**Issue by nethawk2** [jeanmarc77/meterN#19]
Hello,
one of my parameters is the voltage of my battery system. If it is full, then i have 53,2 Volt, if it is empty the voltage
is around 48 Volt.

The standard graph has a scaling, which doesn't show the small range of voltage well.
However, if i zoom (to near the full day) or let me show the details page, the scaling is great.

How can i get for such a parameter in the main page a scaling like in the zoomed or detail graph ?

Thank you
Greetings Torsten

Standard:
![metern-std](https://github.com/jeanmarc77/meterN/assets/52479299/73b04906-f077-496b-90ef-fcadd06c7662)

Zoomed:
![metern-zoomed](https://github.com/jeanmarc77/meterN/assets/52479299/f3ee7a3a-671d-4223-813e-cef72599ceb9)

Detail:
![metern-detail](https://github.com/jeanmarc77/meterN/assets/52479299/55b08096-0ad0-4b03-b131-128e7d688e8d)

**Comment by jeanmarc77** [comment]
Hi,
Did you set as 'sensor' type ?

**Comment by nethawk2** [comment]
Yes, i think so.

![metern-set](https://github.com/jeanmarc77/meterN/assets/52479299/65098c57-fa5b-4822-b205-e3ef955aeb19)

**Comment by jeanmarc77** [comment]
Try removing line 290, softMin: 0
https://github.com/jeanmarc77/meterN/blob/main/index.php

**Comment by nethawk2** [comment]
This works really good, exactly the way i want it.
Thank You
Greetings Torsten

![metern-scnew](https://github.com/jeanmarc77/meterN/assets/52479299/14ac8f3e-9e7c-429f-9135-fe7c11b7bae3)
