### ISSUE TITLE
Last 15 days wrong data

### ISSUE THREAD

**Issue by gianfrdp** [jeanmarc77/meterN#2]
I'm trying latest commit [f58fbb0](https://github.com/jeanmarc77/meterN/commit/f58fbb07baa03f8a41fc1db8da2c02012fd37fd8).
On last 15 days I have 2 meters with same data.

Executing
` curl "http://localhost/metern/programs/programlastdays.php"`
I have wrong results, 
instead using
`curl http://localhost/metern/programs/programlastdays2.php`
results are correct.

Wrong results:
`{"data":[{"name":"PDC","color":"#A6792B","yAxis":0,"data":[[1644969600000,9.746],[1645056000000,13.916],[1645142400000,10.792],[1645228800000,7.184],[1645315200000,10.036],[1645401600000,10.526],[1645488000000,11.45],[1645574400000,10.702],[1645660800000,8],[1645747200000,8.978],[1645833600000,15.318],[1645920000000,12.496],[1646006400000,10.102],[1646092800000,19.784],[1646179200000,11.684]]},{"name":"FV","color":"#1F78FF","yAxis":0,"data":[[1644969600000,23.747],[1645056000000,24.332],[1645142400000,27.319],[1645228800000,21.827],[1645315200000,8.988],[1645401600000,16.424],[1645488000000,30.48],[1645574400000,29.593],[1645660800000,29.066],[1645747200000,28.616],[1645833600000,4.552],[1645920000000,7.006],[1646006400000,11.082],[1646092800000,9.988],[1646179200000,30.779]]},{"name":"Contatore","color":"#FFFFFF","yAxis":0,"data":[[1644969600000,23.747],[1645056000000,24.332],[1645142400000,27.319],[1645228800000,21.827],[1645315200000,8.988],[1645401600000,16.424],[1645488000000,30.48],[1645574400000,29.593],[1645660800000,29.066],[1645747200000,28.616],[1645833600000,4.552],[1645920000000,7.006],[1646006400000,11.082],[1646092800000,9.988],[1646179200000,30.779]]}]}`

correct results:
`{"data":[{"name":"PDC","color":"#A6792B","yAxis":0,"data":[[1644969600000,9.746],[1645056000000,13.916],[1645142400000,10.792],[1645228800000,7.184],[1645315200000,10.036],[1645401600000,10.526],[1645488000000,11.45],[1645574400000,10.702],[1645660800000,8],[1645747200000,8.978],[1645833600000,15.318],[1645920000000,12.496],[1646006400000,10.102],[1646092800000,19.784],[1646179200000,11.684]]},{"name":"FV","color":"#1F78FF","yAxis":0,"data":[[1644969600000,23.747],[1645056000000,24.332],[1645142400000,27.319],[1645228800000,21.827],[1645315200000,8.988],[1645401600000,16.424],[1645488000000,30.48],[1645574400000,29.593],[1645660800000,29.066],[1645747200000,28.616],[1645833600000,4.552],[1645920000000,7.006],[1646006400000,11.082],[1646092800000,9.988],[1646179200000,30.779]]},{"name":"Contatore","color":"#FFFFFF","yAxis":0,"data":[[1644969600000,29.078],[1645056000000,34],[1645142400000,27.609],[1645228800000,21.477],[1645315200000,28.101],[1645401600000,29.313],[1645488000000,30],[1645574400000,30.793],[1645660800000,21.312],[1645747200000,28.75],[1645833600000,32.906],[1645920000000,26.227],[1646006400000,31.148],[1646092800000,34.973],[1646179200000,28.207]]}]}`

**Comment by jeanmarc77** [comment]
Hi,
commit [f58fbb0](https://github.com/jeanmarc77/meterN/commit/f58fbb07baa03f8a41fc1db8da2c02012fd37fd8) is about style.
I don't get issue requesting programs/programlastdays.php.
programlastdays2.php was work in progress.
Can you check again ?

**Comment by gianfrdp** [comment]
Hello, I cloned last available commit.

Today data is correct, I don't understand why 2 days ago was wrong.

But I have another issue: total of day is wrong on page 
![image](https://user-images.githubusercontent.com/10621975/156892493-3fc804a1-79a2-49f4-b553-5b003e8862d2.png)

`curl "http://localhost/metern/programs/programmeter.php" | jq '.title'`

returns

`[
  " PDC (10,47 kWh/4,71€) - FV (5,96 kWh/2,40€) - Contatore (22,45 kWh/10,10€) ",
  " OLD_PDC (0 Wh) - TEMP0 (21,44 °C) - Prelievi (0 Wh) - Temperature (20,70 °C) - Humidity (39,00 %) "
]`

but

`curl "http://localhost/metern/programs/programtotal.php"`

returns

`{"Totalcounter1":"18.779,856 k","Dailycounter1":"9,0 k","Totalcounter2":"87.661,311 k","Dailycounter2":"6,0 k","Totalcounter3":"--","Dailycounter3":"--","Totalcounter4":"--","Dailycounter4":"--","Totalcounter5":"--","Dailycounter5":"--","Totalcounter6":"--","Dailycounter6":"--","Totalcounter7":"--","Dailycounter7":"--","Totalcounter8":"52.043,215 k","Dailycounter8":"17,1 k"}`

First ones are wrong, but second ones are correct:

- Daily counter 1 (PDC) should be 9k, not 10.47k
- Daily counter 8 (Contatore) should be 17.1k, not 22.5k
![image](https://user-images.githubusercontent.com/10621975/156892942-daa94231-093c-4d4b-affd-dc191249135e.png)

**Comment by jeanmarc77** [comment]
programmeter.php is 24h
programtotal is daily value
Please don't use git for help, i don't have much time for that.
It's only for reals issues or enhancement

**Comment by gianfrdp** [comment]
Ok, I was upgrading from version 0.7.5 to 1.3.2.1.
In 0.7.5 page was showing Daily Total, so I tougth there was a bug, I didn't know this behavoir change.
Thanks, anyway

**Comment by jeanmarc77** [comment]
latest is 1.8.4.4, always use latest i don't have time to waste for previous releases.
Please only use github's issues for bugs and enhancements.

**Comment by gianfrdp** [comment]
I'm sorry I wrote wrong version number: I meant I was upgrading from 0.7.5 to [1.2.3.2](https://github.com/jeanmarc77/meterN/releases/tag/1.2.3.2) (latest one),and behavoir on those 2 version is different, so I tought there was a bug on the latter.

![image](https://user-images.githubusercontent.com/10621975/156916454-1e1df4da-df05-4272-ab1a-a63a69c0cc3b.png)

![image](https://user-images.githubusercontent.com/10621975/156916475-52ab98b5-6000-4012-9220-f60a72531b99.png)

I didn't want to disturb you, but this is latest version on GitHub and I cloned directly from github, so it is supposed this is latest version, not a old one
`git clone https://github.com/jeanmarc77/meterN`

commit [f58fbb0](https://github.com/jeanmarc77/meterN/commit/f58fbb07baa03f8a41fc1db8da2c02012fd37fd8) is supposed to be latest at the moment.

I don't see any reference to version 1.8.4.4. If github is not latest version, where I can find it?
Maybe you are referring to latest version of 123solar?

![image](https://user-images.githubusercontent.com/10621975/156915585-3b34fef2-dd18-49e6-aae0-9c6923f7c53e.png)

it was not my intention to waste your time, next time I will modify code by myself and submit a pull request if I find a bug

**Comment by jeanmarc77** [comment]
Hi,
No trouble, I thought you talked about 123s version. 1.2.3.2 is indeed latest mN release.
0.7.5 is so old : 7 years ! that i really don't care about it. There was many changes/improvement since then.

Cloning GitHub is like alpha or beta.. There was several commits since and f58fbb0 is one of them.
So, cloning is safe but it is still suppose to be work in progress until i make a new release package.
cheers

**Comment by gianfrdp** [comment]
In my opinion, should be more useful to have a development branch and leave main for stable releases. When ready merge development with main for a new release.
Regards

**Comment by jeanmarc77** [comment]
stable releases are done via updater ¯\_(ツ)_/¯
