### ISSUE TITLE
help new configuration

### ISSUE THREAD

**Issue by wifi75** [jeanmarc77/meterN#22]
Hi I hope you can help me.
I have two photovoltaic systems, one with a battery and the other without,
I want to have only MeterN to read everything.
I have five RS485 meters that I read with the sdm120c script. Configured like this addess 
meter 2 =FV 1
meter 3= PV 2
meter 4= consumption
meter 5= electric car consumption
meter 6= PDC consumption

which Comapp should I use to have the following sensors configured like this:

sensor 1= total of the two PV
sensor 2= PV1
sensor 3= PV2
sensor 4= total home consumption
sensor 5= electric car consumption
sensor 6= PDC consumption
sensor 7= selfcpower
sensor 8= import
sensor 9= export

**Comment by jeanmarc77** [comment]
Sorry, no support for com apps. I really don't have times for that
