### ISSUE TITLE
update issue with github moving

### ISSUE THREAD

**Issue by megamarco833** [jeanmarc77/meterN#3]
hi JM, 
i'm on meterN version 1.2.3
if i try to update i receive this error:
`Time out: can't retreive https://metern.org/latest_version.php`
it should be generate by moving from metern.org to github.
i see that there is a revision 1.2.3.2 that should solve this issue, but right now how i can update my metern?

second note:
i see that new web link is:
`$url = 'https://raw.githubusercontent.com/jeanmarc77/meterN/main/other/latest_version.json';`
but if i copy paste this link on web page i see:
404: Not Found

it should not be:
`https://raw.githubusercontent.com/jeanmarc77/meterN/1.2.3.2/other/latest_version.json`
in this case i receive in web browser:
```
{
    "LASTVERSION": "meterN 1.2.3",
    "LINK": "https://github.com/jeanmarc77/meterN/releases/download/1.2.3/metern1.2.3.tar.gz",
    "md5": "d691a8f691f74435a71d099299de71d4"
}
```
so, is it correct the url reported in new release inside: `/metern/admin/update.php` ?
and how to update starting from my release?

------------------------------------------------
last question for 123solar
i'm on release [123Solar 1.8.4.3]
if i click on update i see:
You are running 123Solar 1.8.4.3, 123Solar 1.8.4.4 is available

but if i look inside my local raspberry /var/www/123solar/admin/update-php
i see
$url = 'https://123solar.org/latest_version.php';

is it correct? can i proceed on update 123solar and the file will be taken from github?

**Comment by jeanmarc77** [comment]
Hi Marco,
You should have update while the domain was up, 123solar.org will close in few days. 
The url is https://raw.githubusercontent.com/jeanmarc77/meterN/main/misc/latest_version.json but there is also fews changes that need to be done in the code.
The easyest is to manually update mN is [here](https://github.com/jeanmarc77/meterN/wiki/FAQs#how-to-update-)
For 123s you can update till the domain is up

**Comment by megamarco833** [comment]
> Hi Marco, You should have update while the domain was up, 123solar.org will close in few days. The url is https://raw.githubusercontent.com/jeanmarc77/meterN/main/misc/latest_version.json but there is also fews changes that need to be done in the code. The easyest is to manually update mN is [here](https://github.com/jeanmarc77/meterN/wiki/FAQs#how-to-update-) For 123s you can update till the domain is up

thanks JM
ok tomorrow i'll update my 123solar from 1.8.4.3 to 1.8.4.4 with automatic process :)
i'll do manually meteN from 1.2.3 to 1.2.3.2
just to make sure to do the righ command (i'm not so skilled with console) are these correct:
stop metern service
```
cd /var/www/
sudo mkdir metern_backup
sudo cp -rp /var/www/meten/config /var/www/metern_backup/config
sudo cp -rp /var/www/meten/data /var/www/metern_backup/data
wget https://github.com/jeanmarc77/meterN/releases/download/1.2.3.2/metern1.2.3.2.tar.gz  
sudo tar -xzvf metern1.2.3.2.tar.gz 
sudo cp -rp /var/www/metern_backup/config /var/www/metern/config
sudo cp -rp /var/www/metern_backup/data /var/www/metern/data
```
restart metern service
done :)
are these commands correct to get the right owner (www-data) and permissions? (also usage of sudo in some one and not in some others) 

thanks again!

**Comment by jeanmarc77** [comment]
Hi,
You can use SCP to have a file manager.
that sould be

cd /var/www/
sudo mkdir metern_backup
sudo mv /var/www/meten/ /var/www/metern_backup/
wget https://github.com/jeanmarc77/meterN/releases/download/1.2.3.2/metern1.2.3.2.tar.gz  
sudo tar -xzvf metern1.2.3.2.tar.gz 
sudo rm metern1.2.3.2.tar.gz 
sudo cp -rp /var/www/meten/data /var/www/metern_backup/data
sudo cp -rp /var/www/metern_backup/config /var/www/metern/config
sudo chown -R www-data:www-data /var/www/metern/
and restart from admin

**Comment by megamarco833** [comment]
thanks as always Jeanmarc!
just a correction of a couple of commands that i run:
stop metern
```
cd /var/www/
sudo mkdir metern_backup
sudo mv /var/www/metern/ /var/www/metern_backup/
sudo wget https://github.com/jeanmarc77/meterN/releases/download/1.2.3.2/metern1.2.3.2.tar.gz
sudo tar -xzvf metern1.2.3.2.tar.gz
sudo rm metern1.2.3.2.tar.gz
sudo cp -rp /var/www/metern_backup/data /var/www/metern/data
sudo cp -rp /var/www/metern_backup/config /var/www/metern/config
sudo chown -R www-data:www-data /var/www/metern/
```
and restart from admin

thanks to your help I succeed on update manually metern and now i'm on the latest version
thanks again, ciao
Marco
