### ISSUE TITLE
having "null" value on a meter

### ISSUE THREAD

**Issue by ptoni2000** [jeanmarc77/meterN#6]
I would like to know if possible to put a "null" value in a meter to not display it in the graph,
this is the case: a temperature detected by micro inverters that do not respond to polling at night,
simply putting 0 is not good as it is a valid value.

**Comment by jeanmarc77** [comment]
Hi,
You mean for a "sensor" ?
If so, i believe you will get "Communication error", if you return a null value if you enable "Warn connection lost".
Can you git it a try ?

**Comment by ptoni2000** [comment]
You see the graph for temperature on https://casa.tonitabaro.net/metern/
i would like to have on the graph during the night someting like: https://www.highcharts.com/demo/area-missing

**Comment by jeanmarc77** [comment]
Ok i get the idea, it's neat..
But the problem is with testing "Communication error", if a meter/sensor returns null. How can i detect it ?

**Comment by ptoni2000** [comment]
what if using nan or someting like the "c" FLT_MAX as a value?

**Comment by jeanmarc77** [comment]
Hi,
Can you give a try using this https://github.com/jeanmarc77/meterN/blob/main/scripts/datasets/IEC62056.php and https://github.com/jeanmarc77/meterN/blob/main/scripts/metern.php ?

**Comment by ptoni2000** [comment]
> Hi, Can you give a try using this https://github.com/jeanmarc77/meterN/blob/main/scripts/datasets/IEC62056.php and https://github.com/jeanmarc77/meterN/blob/main/scripts/metern.php ?

works great, thanks!
