### ISSUE TITLE
get total solar kWh for today

### ISSUE THREAD

**Issue by speeskeek** [jeanmarc77/meterN#7]
hello

very happy with metern and solar123.
I'm using it since a year for gas (m3) and solar production.

recently I installed a 3Pase Orno power meter and reading it with help of https://github.com/volkszaehler/mbmd. that works great ! very happy to check my consumption.

No I want to make an (arduino) powered LCD to put on my wall, kitchen top, ... where the LCD shows the actual (momentarily) values of the actual power production vs consumption. But also the consumption for today and the production for today.

I managed to get the momentarily (Wh) values by making a copy and adapted verion of the pool123s-script. But the kWh values for the day (starting at midnight?) I don't manage to get out of metern. 

any help is appreciated.

**Comment by jeanmarc77** [comment]
Hi,
You can make the difference between FirstX and LastX values in /dev/shm/mN_MEMORY.json

**Comment by speeskeek** [comment]
okay - so the difference between Last1 - First1 = my gas consumption since midnight? And how about the last 24h (like showed on the web interface? 4,08m3 7,57kWh and 17,49 kWh) ?


![Naamloos](https://user-images.githubusercontent.com/8826404/216944667-d548f615-6289-4a2c-8ad1-2ebf97b80951.png)


( now I learned I can all the live values easely too from /mN_LIVEMEMORY.json  :) )

**Comment by jeanmarc77** [comment]
you cannot get last 24h values from mN_LIVEMEMORY.json, you have to write a script that fetch from csv

**Comment by speeskeek** [comment]
Thank you. 

Need to work on the layout … but linking those /dev/shm/…..json to my public web makes my job pretty easy displaying this over wifi on an lcd!

![343E760E-4328-436F-80F9-0CC944B14304](https://user-images.githubusercontent.com/8826404/218282765-5290f258-e933-412d-807d-33176cf43b7e.jpeg)

very happy .. but need to seek a good layout

**Comment by jeanmarc77** [comment]
congrats ! :) Maybe you can share your code

**Comment by speeskeek** [comment]
so I made a symlink in linux (ln -s /dev/shm/mN_Memory.json /var/www/mn_mem.json) I did the same for the other (live) one.
Make sure the json is accesible over wifi/local lan.

then I wrote this code. Not winning any beauty contests with it, but it works.
I'm using a Wemos D1 (clone) (see ali-express) and running esp8266 via arduino IDE (so you need to add the board to arduino).
For that, I got a lot of info from this great site: [https://siytek.com/wemos-d1-mini-arduino-wifi/](click url)


my code:
`
#include <ESP8266WiFi.h>
#include <ArduinoJson.h>
#include <ArduinoHttpClient.h>
#include <Wire.h>
#include <LiquidCrystal_I2C.h>

// Set WiFi credentials
#define WIFI_SSID "YOUR_WIFI" //edit this to fit your situation
#define WIFI_PASS "YOUR_WIFI_PASS"  //edit this to fit your situation
WiFiClient wifi;

char serverAddress[] = "192.168.1.240";  //edit this to fit your situation, IP adress of the server where the symlinks are accessible
int port = 80;

HttpClient client = HttpClient(wifi, serverAddress, port);
LiquidCrystal_I2C lcd(0x27, 20, 4);

void setup() {
  Serial.begin(9600);  
  pinMode(LED_BUILTIN, OUTPUT);
  lcd.init();
  lcd.init();
  lcd.backlight();
  lcd.setCursor(0, 0);
  lcd.print("   Hallo   ");
  lcd.setCursor(0, 3);
  lcd.print("Bart Marivoet - 2023"); // my copyright :) my 5 sec of fame 
  delay(100);
  digitalWrite(LED_BUILTIN, LOW);
  lcd.clear();
  
  WiFi.begin(WIFI_SSID, WIFI_PASS);
  lcd.setCursor(0, 0);
  lcd.print("Connecting to ");
  lcd.setCursor(0, 1);
  lcd.print(WIFI_SSID);
  int i=0;
  while (WiFi.status() != WL_CONNECTED)
  {
    delay(450);
    lcd.setCursor(i,2);
    lcd.print(".");
    Serial.print(".");
    i++;  
  }

  Serial.println("");
  digitalWrite(LED_BUILTIN, HIGH);
  Serial.println("Connected!");
  Serial.print("IP address:  ");
  Serial.println(WiFi.localIP());
  lcd.clear();
  lcd.setCursor(0, 0);
  lcd.print("Connected !");
  lcd.setCursor(0, 2);
  lcd.print("mijn IP");
  lcd.setCursor(0, 3);
  lcd.print(WiFi.localIP()); //show the IP adress - so you're sure it's connected
  digitalWrite(LED_BUILTIN, HIGH);
}

void loop() {
  client.get("/mn_live.json");  //edit this to fit your situation, if the symlink has another name or is in a subdir
  delay(50);
  String response = client.responseBody();

  StaticJsonDocument<384> doc;
  DeserializationError error = deserializeJson(doc, response);

  //maybe your sensor data has another name. edit according your needs
  long UTC = doc["UTC"]; // 1676122420
  const char* Gas1 = doc["Gas1"]; // "34135.830"
  const char* Buitentemperatuur2 = doc["Buitentemperatuur2"]; // "8"
  float PV_panelen3 = doc["PV panelen3"]; // "308.7"
  int Netstroom7 = doc["Netstroom7"]; // "637"


  client.get("/mn_mem.json");   //edit this to fit your situation, if the symlink has another name or is in a subdir
  delay(50);
  String response2 = client.responseBody();

  StaticJsonDocument<768> doc2;
  DeserializationError error2 = deserializeJson(doc2, response2);
  float First1 = doc2["First1"];
  float Last1 = doc2["Last1"]; 
  long First7 = doc2["First7"];
  long Last7 = doc2["Last7"]; 
  long First3 = doc2["First3"];
  long Last3 = doc2["Last3"]; 
  
  //edit according your situation. gasverbruik = gas consumption, opwekking = production of PV, verbruik= electric consumption
  float gasverbruik = Last1 - First1;
  double opwekking = (Last3 - First3);
  double opwekking2 = opwekking / 1000;
  double verbruik = (Last7 - First7);
  double verbruik2 = verbruik / 1000;
  
  int PV3 = PV_panelen3 + 1 - 1;
  lcd.clear();
  lcd.setCursor(0, 1);
  lcd.print("Ep");
  lcd.setCursor(3, 1);
  lcd.print(PV3);
  lcd.setCursor(8, 1);
  lcd.print("W");  
  lcd.setCursor(11, 1);
  lcd.print(opwekking2);
  lcd.setCursor(17, 1);
  lcd.print("kWh");
  
  lcd.setCursor(0, 0);
  lcd.print("Gas ");
  lcd.setCursor(11, 0);
  lcd.print(gasverbruik);
  lcd.setCursor(18, 0);
  lcd.print("m3");
  
  
  lcd.setCursor(0, 2);
  lcd.print("Ec");
  lcd.setCursor(3, 2);
  lcd.print(Netstroom7);
  lcd.setCursor(8, 2);
  lcd.print("W");
  lcd.setCursor(11, 2);
  lcd.print(verbruik2);
  lcd.setCursor(17, 2);
  lcd.print("kWh");  

  double net_tot = verbruik2 - opwekking2;
  int net_live = Netstroom7 - PV_panelen3;
  lcd.setCursor(0, 3);
  lcd.print("En");
  if (net_live < 0) {
    lcd.setCursor(2, 3);  
  }
  else {
    lcd.setCursor(3, 3);
  }
  lcd.print(net_live);
  lcd.setCursor(8, 3);
  lcd.print("W");

  if (net_tot < 0) {
    lcd.setCursor(10, 3);  
  }
  else {
    lcd.setCursor(11, 3);
  }
  
  lcd.print(net_tot);
  lcd.setCursor(17, 3);
  lcd.print("kWh");  
 
  
  //just making a kind of heartbeat led, so I know it's still alive. In total wait 2 secs befor updating the whole shabang
  digitalWrite(LED_BUILTIN, LOW);
  delay(100);
  digitalWrite(LED_BUILTIN, HIGH);
  delay(80);
  digitalWrite(LED_BUILTIN, LOW);
  delay(100);
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1720);
  
}
`

**Comment by speeskeek** [comment]
current layout....

Ep = Electricity Producion (solar)
Ec = Electricity Consumption
En = Electricity Netto (difference between the two)
![SOTC_202302c6387](https://user-images.githubusercontent.com/8826404/218308737-378c6a90-eba1-4f58-9495-4e36c1d16f9e.jpg)

**Comment by jeanmarc77** [comment]
looks really neat, thank you
