### ISSUE TITLE
graph of netto between grid power and solar power

### ISSUE THREAD

**Issue by speeskeek** [jeanmarc77/meterN#9]
hi

is there a possibility to add a graph (or how do I have to create a commapp?) to have graph (that can go below zero) of the actual consumtion. the graph goes as posibitve or as negative to show the amount of injection or grid consumption

= 0 being consumption =. production
< 0 is more production (so injection on the public grid)
> 0 is consumption (so using the public grid - probably at night when there is no sun :) )

so actually a line that makes the substraction between my red (grid energy) and green (solar panels energy) graph

![Naamloos](https://user-images.githubusercontent.com/8826404/232323604-0df7d6d9-fb78-4cca-bb3a-6ab8665faea4.png)

I tried making a commapp for this, but helas it's not doing what I like.

**Comment by jeanmarc77** [comment]
Hi,
Simple answer : no. A meter shall always increase as stated in the [wifi](https://github.com/jeanmarc77/meterN/wiki/3)-How-to)
I have two meters for that purpose, one with imported energy the other for exported.
Also, to know the hould self-consumption i create [houseenergy.php](https://github.com/jeanmarc77/meterN_comapps/blob/main/daemon/houseenergy.php)
So, you can do whatever but simply don't count backward.
